import {
  type CSSProperties,
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
} from "react";
import { FitAddon } from "@xterm/addon-fit";
import { Terminal } from "@xterm/xterm";
import { SendHorizontal } from "lucide-react";
import { terminalTheme } from "../lib/terminal-theme";
import {
  serviceLabels,
  type ServiceId,
  type ServiceState,
} from "../types/launcher";

export interface TerminalPanelHandle {
  clear: () => void;
  write: (text: string) => void;
  dimensions: () => { columns: number; rows: number };
}

interface TerminalPanelProps {
  serviceId: ServiceId;
  state: ServiceState;
  onCommand: (text: string) => Promise<boolean>;
  onCopyError: (error: unknown) => void;
  onCtrlC: () => void;
  onResize: (columns: number, rows: number) => void;
  onTerminalData: (data: string) => void;
}

// Keep the xterm gutter narrow while leaving one device pixel for the thumb
// and its hover state at normal Windows scaling.
const TERMINAL_SCROLLBAR_WIDTH = 4;

export const TerminalPanel = forwardRef<
  TerminalPanelHandle,
  TerminalPanelProps
>(function TerminalPanel(
  { serviceId, state, onCommand, onCopyError, onCtrlC, onResize, onTerminalData },
  ref,
) {
  const hostRef = useRef<HTMLDivElement>(null);
  const terminalRef = useRef<Terminal | null>(null);
  const stateRef = useRef(state);
  const resizeCallbackRef = useRef(onResize);
  const ctrlCCallbackRef = useRef(onCtrlC);
  const terminalDataCallbackRef = useRef(onTerminalData);
  const copyErrorCallbackRef = useRef(onCopyError);
  const [command, setCommand] = useState("");

  // xterm is created once. Mutable refs keep callbacks and service state fresh
  // without destroying terminal history whenever React renders new props.
  stateRef.current = state;
  resizeCallbackRef.current = onResize;
  ctrlCCallbackRef.current = onCtrlC;
  terminalDataCallbackRef.current = onTerminalData;
  copyErrorCallbackRef.current = onCopyError;

  useImperativeHandle(ref, () => ({
    // Terminal output bypasses React state so high-volume service logs do not
    // trigger reconciliation of the entire application.
    clear: () => terminalRef.current?.clear(),
    write: (text: string) => terminalRef.current?.write(text),
    dimensions: () => ({
      columns: terminalRef.current?.cols ?? 80,
      rows: terminalRef.current?.rows ?? 24,
    }),
  }));

  useEffect(() => {
    const host = hostRef.current;
    if (!host) return undefined;

    const terminal = new Terminal({
      allowProposedApi: false,
      // ConPTY already controls line endings; xterm must not insert extra CRLFs.
      convertEol: false,
      cursorBlink: false,
      cursorInactiveStyle: "none",
      // xterm must be allowed to answer terminal protocol requests such as
      // CSI 6 n (cursor-position report). Some Windows console programs wait
      // for that response before writing any visible output. User input is
      // blocked separately below so these service terminals remain read-only.
      disableStdin: false,
      fontFamily: '"Cascadia Mono", Consolas, monospace',
      fontSize: 13,
      lineHeight: 1.12,
      // xterm and FitAddon share this width, so the last text column is
      // measured before the scrollbar instead of rendering underneath it.
      overviewRuler: { width: TERMINAL_SCROLLBAR_WIDTH },
      scrollback: 5000,
      smoothScrollDuration: 100,
      theme: terminalTheme,
    });
    const fitAddon = new FitAddon();
    terminal.loadAddon(fitAddon);
    terminal.open(host);
    // Keep the hidden input read-only without using xterm's disableStdin
    // option, which would also suppress replies generated by the ANSI parser.
    if (terminal.textarea) terminal.textarea.readOnly = true;
    terminalRef.current = terminal;
    const dataSubscription = terminal.onData((data) => {
      // Read-only terminals still generate protocol replies requested by some
      // console programs, so those bytes must return to ConPTY.
      terminalDataCallbackRef.current(data);
    });

    terminal.attachCustomKeyEventHandler((event) => {
      if (
        event.type === "keydown" &&
        event.ctrlKey &&
        event.key.toLowerCase() === "c"
      ) {
        const selection = terminal.getSelection();
        // Match conventional terminal behavior: copy a selection, otherwise
        // treat Ctrl+C as a request for the service's graceful stop sequence.
        if (selection) {
          if (!navigator.clipboard) {
            copyErrorCallbackRef.current(
              new Error("Clipboard access is unavailable."),
            );
            return false;
          }
          void navigator.clipboard
            .writeText(selection)
            .catch((error) => copyErrorCallbackRef.current(error));
        } else {
          ctrlCCallbackRef.current();
        }
        return false;
      }
      // Commands are accepted only through the dedicated Worldserver command
      // bar. Returning false prevents all other keystrokes from reaching PTY
      // stdin while parser-generated terminal replies still use onData.
      return false;
    });

    const preventUserTextInput = (event: Event) => {
      event.preventDefault();
      event.stopPropagation();
    };
    // Key handlers do not cover paste, IME composition, or drag-and-drop.
    // Capture those paths before xterm can translate them into PTY input.
    host.addEventListener("beforeinput", preventUserTextInput, true);
    host.addEventListener("paste", preventUserTextInput, true);
    host.addEventListener("drop", preventUserTextInput, true);

    let resizeTimer: ReturnType<typeof setTimeout> | undefined;
    const fit = () => {
      clearTimeout(resizeTimer);
      // Layout can fire several ResizeObserver callbacks in one frame. Debounce
      // them to avoid flooding the native PTY with intermediate dimensions.
      resizeTimer = setTimeout(() => {
        fitAddon.fit();
        if (stateRef.current !== "idle") {
          resizeCallbackRef.current(terminal.cols, terminal.rows);
        }
      }, 80);
    };
    const observer = new ResizeObserver(fit);
    observer.observe(host);
    fit();

    return () => {
      // Dispose every subscription owned by this mount so development remounts
      // and application shutdown cannot retain hidden terminals or observers.
      clearTimeout(resizeTimer);
      observer.disconnect();
      host.removeEventListener("beforeinput", preventUserTextInput, true);
      host.removeEventListener("paste", preventUserTextInput, true);
      host.removeEventListener("drop", preventUserTextInput, true);
      dataSubscription.dispose();
      terminal.dispose();
      terminalRef.current = null;
    };
  }, []);

  async function submitCommand() {
    const text = command.trim();
    if (!text || state !== "running") return;
    if (await onCommand(text)) setCommand("");
  }

  const inputEnabled = serviceId === "worldserver";

  return (
    <section className="terminal-panel" data-state={state}>
      <header className="terminal-panel__header">
        <span
          className="status-dot"
          role="status"
          aria-label={`${serviceLabels[serviceId]} ${state}`}
        />
        <h2>{serviceLabels[serviceId]}</h2>
      </header>
      <div className="terminal-panel__viewport">
        {/* FitAddon measures xterm's direct parent, so visual padding and
            borders must remain on the outer frame to avoid phantom columns. */}
        <div
          className="terminal-panel__host"
          ref={hostRef}
          aria-label={`${serviceLabels[serviceId]} terminal output`}
          style={
            {
              "--terminal-scrollbar-width": `${TERMINAL_SCROLLBAR_WIDTH}px`,
            } as CSSProperties
          }
        />
      </div>
      {inputEnabled && (
        <div className="terminal-input">
          <input
            aria-label="Worldserver command"
            autoComplete="off"
            disabled={state !== "running"}
            onChange={(event) => setCommand(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Enter") void submitCommand();
            }}
            placeholder="Type a command..."
            value={command}
          />
          <button
            aria-label="Send Worldserver command"
            className="control-button terminal-input__send"
            disabled={state !== "running" || !command.trim()}
            onClick={() => void submitCommand()}
            type="button"
          >
            <SendHorizontal aria-hidden="true" size={17} />
          </button>
        </div>
      )}
    </section>
  );
});
